services:
  postgres:
    image: postgres:16
    ports:
      - '5450:5432'
    environment:
      POSTGRES_DB: markado
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 